backend:
  name: git-gateway
  branch: main

media_folder: "src/static/uploads"
public_folder: "/static/uploads"


collections:
  - name: "years"
    label: "Ročníky"
    folder: "src/years"
    create: true
    slug: "{{year}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Body", name: "body", widget: "text" }
      - label: "Vysledky"
        name: "vysledky"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "From", name: "from", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Link", name: "link", widget: "string" }
      - { label: "Video", name: "video", widget: "string" }